# Generated by Django 3.2.3 on 2021-06-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210615_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='gjson',
            field=models.JSONField(),
        ),
    ]
